name: Reusable Release workflow

on:
  workflow_call:
    inputs:
      pre-release-mode:
        description: "Whether or not to tag versions as pre-release versions"
        required: false
        type: boolean
      before-release-script:
        description: "Path to a custom script in the repository that runs before release"
        required: false
        type: string
        
jobs:

  make-release:
    uses: ./.github/workflows/make-release.yml
    secrets: inherit
    with:
      pre-release-mode: ${{ inputs.pre-release-mode }}
      before-release-script: ${{ inputs.before-release-script }}
