name: Make Release

on:
  workflow_call:
    inputs:
      pre-release-mode:
        description: "Whether or not to tag versions as pre-release versions"
        required: false
        type: boolean
      before-release-script:
        description: "Path to a custom script in the repository that runs before release"
        required: false
        type: string

jobs:
  changelog-and-release:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ github.token }}
          fetch-depth: 0

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6.0.0
        with:
          github-token: ${{ github.token }}
          skip-version-file: 'true'
          fallback-version: '1.0.0'
          skip-commit: 'true'
          tag-prefix: ''
          pre-release: "${{ inputs.pre-release-mode }}"

      - name: Stop if needed
        if: ${{ steps.changelog.outputs.changelog == null }}
        run: exit 1

      - name: Run custom script before Release
        if: inputs.before-release-script != ''
        env:
          NEW_TAG: ${{ steps.changelog.outputs.tag }}
        run: |
          script="${{ inputs.before-release-script }}"
          if [ -f "$script" ]; then
            chmod +x "$script"
            "$script"
          else
            echo "Custom pre-release script not found"
            exit 1
          fi

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          prerelease: ${{ inputs.pre-release-mode }}
