name: Make Release

on:
  workflow_call:
    inputs:
      pre-release-mode:
        description: "Whether or not to tag versions as pre-release versions"
        required: false
        type: boolean
      
      pre-commit-hook:
        description: "Path to a custom pre-release script in the repository"
        required: false
        type: string

jobs:
  changelog-and-release:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ github.token }}
          fetch-depth: 0

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6.0.0
        with:
          github-token: ${{ github.token }}
          skip-version-file: 'true'
          fallback-version: '1.0.0'
          skip-commit: 'true'
          tag-prefix: ''
          pre-release: "${{ inputs.pre-release-mode }}"
          pre-commit: "${{ inputs.pre-commit-hook }}"

      - name: Stop if needed
        if: ${{ steps.changelog.outputs.changelog == null }}
        run: exit 1

      #- name: Run Custom Pre-Release Script
      #  if: inputs.custom-pre-release-script != ''
      #  env:
      #    NEW_TAG: ${{ steps.changelog.outputs.tag }}
      #  run: |
      #    if [ -f "${{ inputs.custom-pre-release-script }}" ]; then
      #      chmod +x "${{ inputs.custom-pre-release-script }}"
      #      "${{ inputs.custom-pre-release-script }}"
      #    else
      #      echo "Custom pre-release script not found"
      #      exit 1
      #    fi

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          prerelease: ${{ inputs.pre-release-mode }}
